spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.6.134:3306/sneaklifedb?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT&rewriteBatchedStatements=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    timeout: 7000ms
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 10
        min-idle: 5
    host: 192.168.6.134
    port: 6388
    password: 123456qwe

  session:
    store-type: redis
    timeout: 30m
    redis:
      namespace: redis:session

  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/sneakLifeLogDB
