spring:
  mvc:
    dispatch-options-request: true
  profiles:
    active: dev

  datasource:
    druid:
      initial-size: 5
      minIdle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j2
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
#  type-aliases-package: com.sneaklife.pms.entity
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

rsa:
  key_algorithm: RSA
  cipher_algorithm: RSA/ECB/PKCS1Padding
  signature_algorithm: SHA1withRSA
  public_key: puk
  private_key: prk
  signature_name: SIGNATURE_NAME
  max_encrypt_block: 117
  max_decrypt_block: 128

aes:
  key_algorithm: AES/ECB/PKCS5Padding
  signature_name: AES
  charset: utf-8

common:
  token_cache_times: 30
  token_key: TOKEN_KEY
  server_url: http://127.0.0.1:8080/sneakLife-admin/service
  serverPathYzm: http://192.168.6.134:9090/sneakLife-admin/yzm/
  filePathYzm: D:\\Compressed\\JCV\\Tomcat\\webapps\\test\\yzm\\
  user_key: userKey
  user_key_session_times: 1800
  user_cache_dir: user
  xxl_job_path: http://127.0.0.1:8880/xxl-job-admin/


xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8880/xxl-job-admin
    executor:
      appname: sneakLife-xxl-job
      ip:
      port: 8790
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
    accessToken:

